from mcp.server.fastmcp import FastMCP
from typing import Dict, Any
import os
from google import genai
from google.genai import types
from pathlib import Path
import time
import logging

# Set up logging
logger = logging.getLogger(__name__)

mcp = FastMCP("chimera-image")

# Define output directory relative to project root
CURRENT_DIR = Path(__file__).parent
PROJECT_ROOT = CURRENT_DIR.parent.parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "frontend" / "public" / "generated"

def ensure_output_dir():
    try:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        return OUTPUT_DIR
    except Exception as e:
        logger.error(f"Failed to create frontend output dir: {e}")
        # Fallback to local 'generated' folder
        fallback = Path("generated")
        fallback.mkdir(exist_ok=True)
        return fallback

IMAGE_DIR = ensure_output_dir()

@mcp.tool()
def generate_image(prompt: str, character_id: str = "default") -> Dict[str, Any]:
    """
    Generates an image based on the prompt using Google's Imagen model via new SDK.
    
    Args:
        prompt: The description of the image.
        character_id: Optional character consistency ID.
    """
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
         return {
            "status": "error",
            "error": "GOOGLE_API_KEY not found in environment"
        }
    
    try:
        client = genai.Client(api_key=api_key)
        
        # Enhance prompt with character consistency (basic injection)
        full_prompt = prompt
        if character_id != "default":
             full_prompt = f"{prompt} -- Context: Character ID {character_id}, maintain consistent style."

        logger.info(f"Generating image for prompt: {full_prompt}")
        # Using correct method for new SDK
        response = client.models.generate_images(
            model='gemini-2.0-flash-exp-image-generation',
            prompt=full_prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="16:9",
            )
        )
        
        if not response.generated_images:
             return {"status": "error", "error": "No images generated by the model."}

        generated_image = response.generated_images[0]
        image_bytes = generated_image.image.image_bytes
        
        # Save to disk
        timestamp = int(time.time())
        filename = f"{character_id}_{timestamp}.png"
        filepath = IMAGE_DIR / filename
        
        with open(filepath, "wb") as f:
            f.write(image_bytes)
        
        logger.info(f"Saved generated image to {filepath}")

        # Return path suitable for frontend
        if "frontend/public" in str(filepath):
             web_path = f"/generated/{filename}"
        else:
             web_path = str(filepath)

        return {
            "status": "success",
            "local_path": str(filepath),
            "url": web_path,
            "prompt": full_prompt
        }
    except Exception as e:
        logger.warning(f"Image generation failed (likely billing/access): {e}")
        logger.info("Falling back to MOCK generation.")
        
        # Fallback: Create a text file or just return a mock URL
        # For better DX, let's try to make a dummy image file if possible
        timestamp = int(time.time())
        filename = f"mock_{character_id}_{timestamp}.png"
        filepath = IMAGE_DIR / filename
        
        # Create a simple 1x1 pixel image or just a file
        try:
            from PIL import Image
            img = Image.new('RGB', (100, 100), color = 'gray')
            img.save(filepath)
            logger.info(f"Created mock image at {filepath}")
        except ImportError:
            with open(filepath, "w") as f:
                f.write("Mock Image Content")
        
        if "frontend/public" in str(filepath):
             web_path = f"/generated/{filename}"
        else:
             web_path = str(filepath)
             
        return {
            "status": "success",
            "local_path": str(filepath),
            "url": web_path,
            "prompt": prompt,
            "note": "Generated via Mock Fallback (API Error)"
        }

if __name__ == "__main__":
    mcp.run()
